# Define stages
stages:
  - build
  - deploy

# Build Stage
build:
  stage: build
  script:
    - docker build -t fappci .
  only:
    - main  # Only run on the main branch

# Deploy Stage
deploy:
  stage: deploy
  script:
    - docker stop fappci || true  # Stop the container if it's already running
    - docker rm fappci || true    # Remove any old container
    - docker run -d --name fappci -p 5000:5000 -p 5001:5001 fappci  # Run the app in a new container
  only:
    - main  # Only run on the main branch
